openapi: 3.0.0
info:
  title: Auth API
  version: '1.0.0'
  description: Endpoints for authentication
paths:
  /auth/login:
    post:
      summary: Login a user
      tags:
        - Auth
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                email:
                  type: string
                  example: 'user@example.com'
                password:
                  type: string
                  example: 'password123'
              required:
                - email
                - password
      responses:
        200:
          description: Login successful
  /auth/register:
    post:
      summary: Register a user
      tags:
        - Auth
  /auth/logout:
    post:
      summary: Logout a user
      tags:
        - Auth
  /auth/me:
    get:
      summary: Get current user
      tags:
        - Auth
